### ISSUE TITLE
detaching background and apply alpha fill for foreground

### ISSUE THREAD

**Issue by khlukekim** [khlukekim/yellowstonestudio#1]
Composition may help
https://developer.mozilla.org/en-US/docs/Web/API/Canvas_API/Tutorial/Compositing

**Comment by danielrhim** [comment]
Transparency Filter: https://www.w3schools.com/cssref/pr_background-color.asp

**Comment by danielrhim** [comment]
Opacity Filer: https://www.w3schools.com/css/css_image_transparency.asp

**Comment by khlukekim** [comment]
SVG filtering 
https://blogs.msdn.microsoft.com/ie/2011/10/14/svg-filter-effects-in-ie10/

**Comment by khlukekim** [comment]
done by b967c332bcb19eb676033d60019b1840ec462a81
call me genius

**Comment by khlukekim** [comment]
test it here: https://khlukekim.github.io/yellowstonestudio/sketch/testdetachedbg.html

due to the blend mode, the inner white dots in the bg will appear over the foreground image.
this is inevitable, let's make the bg image somewhat darker and blurrier in the center.
